// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'prisma/seed.ts',
  },
  datasource: {
    url:
      'postgresql://' +
      process.env.DB_USERNAME +
      ':' +
      process.env.DB_PASSWORD +
      '@' +
      process.env.DB_HOST +
      ':' +
      process.env.DB_PORT +
      '/payroll-engine?schema=public',
  },
})
